### ISSUE TITLE
InputTextFilterCharacter doesn't filter Tabs (in german system)

### ISSUE THREAD

**Issue by HaSa1002** [ocornut/imgui#2467]
**Version/Branch of Dear ImGui:**

Version: 1.69
Branch: master

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_sfml
Operating System: Windows 10 (**German** as Systemlanguage)

**My Issue:**
You can enter a Tab in any InputText, which will cause a focus jump to the next item, but the tab is also written into the buffer. My tests of the InputTextFilterCharacter (which is my best friend...) proved, that isprint returns 64 if a tab is entered. Why is it necessary to use isprint in that case?

**Standalone, minimal, complete and verifiable example:**
```
ImGui::Begin("Bug");
static char buff[5] = "";
static char buff2[5] = "";
ImGui::InputText("Label", buff, 5);
ImGui::InputText("Label2", buff2, 5);
ImGui::End();
```

**Comment by ocornut** [comment]
I am not sure the SFML back-end is correct emitting both a Key and Char input.

**Comment by HaSa1002** [comment]
How can I check that?

**Comment by ocornut** [comment]
> How can I check that?

Add print out into the SFML code calling `io.AddInputCharacter()` and setting `KeysDown[] = xxx` value. In the printout include the value of `ImGui::GetFrameCount()` so you can see the frame timing at which each is being emitted.

But I was wrong: most back-ends _are_ emitting a `\t` character along with the Tab key. Also see #1336

> that isprint returns 64 if a tab is entered. 

Could you compile this code and confirm the output:
```
    printf("isprint \\t = %d\n", isprint('\t'));
    printf("isprint \\n = %d\n", isprint('\n'));
```

Then provide the exact compiler you are using (which you have omitted from the issue template questions).

Thank you.

**Comment by ocornut** [comment]
Alright, welcome to compiler/std-library hell :)

https://stackoverflow.com/questions/51435249/isprint-t-evaluates-to-true-64-with-md-compiler-option
https://github.com/JuliaLang/julia/issues/7416

I will explicitely work-around around this in the code, thanks!

**Comment by ocornut** [comment]
Fixed this now, thank you for the report! Also probably explains #1336 now!

**Comment by codename-irvin** [comment]
FYI, I am still seeing this issue on Win32/DX12. I have worked around the issue for now by commenting out [this code](https://github.com/ocornut/imgui/blob/master/imgui_widgets.cpp#L4207).

**Comment by ocornut** [comment]
I can confirm there's an issue with the new IO queue trickling events over two frames (#4921) those tests are now invalid.

**Comment by ocornut** [comment]
@codename-irvin can you clarify precisely the issue you are getting? 
I am getting two tabs inserted instead of one.
Are you on a 1.87+ backend?

**Comment by ocornut** [comment]
Fixed by dfbe938e54858b8b443ca2981d037cc2f35cc931

**Comment by codename-irvin** [comment]
@ocornut, indeed. The issue was that I was getting two tabs inserted instead of one. Looks like I am on a 1.88 backend. I am on docking branch latest.
