### ISSUE TITLE
glfw is calling imgui's callbacks but imgui is not responsive

### ISSUE THREAD

**Issue by thegeeko** [ocornut/imgui#4747]
**Version/Branch of Dear ImGui:**

Version: 1.86
Branch: docking

**Back-end/Renderer/Compiler/OS**

Back-ends: imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp _(or specify if using a custom engine/back-end)_
Compiler: gcc
Operating System: arch linux

**My Issue/Question:**

I'm trying to integrate imgui in my engine and I'm using glfw and opengl the problem is the imgui is not responsive at all .. the glfw is calling imgui's call back .. not sure what can be the problem 

**Screenshots/Video**

https://user-images.githubusercontent.com/36560490/142741741-1c627953-5957-4f94-a3fa-8dfded275ea3.mp4
glfw is calling imgui's function

https://user-images.githubusercontent.com/36560490/142741831-832db75d-a4d4-4710-97a7-766caee9f866.mp4
imgui is not responsive at all 

```cpp
// how I'm initing imgui
void ImGuiLayer::onAttach() {
	ImGui::CreateContext();
	ImGuiIO& io = ImGui::GetIO();
	(void)io;
	io.ConfigFlags |= ImGuiConfigFlags_NavEnableKeyboard;		 // Enable Keyboard Controls
	io.ConfigFlags |= ImGuiConfigFlags_DockingEnable;		 // Enable Docking
	io.ConfigFlags |= ImGuiConfigFlags_ViewportsEnable;		 // Enable Multi-Viewport / Platform Windows

	ImGui::StyleColorsDark();

	// When viewports are enabled we tweak WindowRounding/WindowBg so platform windows can look identical to regular ones.
	ImGuiStyle& style = ImGui::GetStyle();
	if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) {
		style.WindowRounding = 0.0f;
		style.Colors[ImGuiCol_WindowBg].w = 1.0f;
	}

	// Setup Platform/Renderer backends
	ImGui_ImplGlfw_InitForOpenGL(App::get().getWindow().getRawWindow(), true);
	ImGui_ImplOpenGL3_Init("#version 430");

	GEG_CORE_INFO("Im gui attached");
}
```

**Comment by ocornut** [comment]
Are you calling the backends _NewFrame() functions correctly and before the ImGui::NewFrame() function? Refer to the provided examples and compare your code carefully to them.

**Comment by thegeeko** [comment]
yes .. and im calling them in the right order just like the example 
```cpp
void ImGuiLayer::begin() {
	ImGui_ImplOpenGL3_NewFrame();
	ImGui_ImplGlfw_NewFrame();
	ImGui::NewFrame();
}

void ImGuiLayer::end() {
	ImGuiIO& io = ImGui::GetIO();
	App& app = App::get();
	io.DisplaySize = ImVec2((float)app.getWindow().getWidth(), (float)app.getWindow().getHeight());

	// Rendering
	ImGui::Render();
	ImGui_ImplOpenGL3_RenderDrawData(ImGui::GetDrawData());

	if (io.ConfigFlags & ImGuiConfigFlags_ViewportsEnable) {
		GLFWwindow* backup_current_context = glfwGetCurrentContext();
		ImGui::UpdatePlatformWindows();
		ImGui::RenderPlatformWindowsDefault();
		glfwMakeContextCurrent(backup_current_context);
	}
}
```
I have begin and end before after every imgui call


and when i start a window twice it's just fine but when i start it just one time or start another window it doesn't work the mouse effects work but it's controllable  .. here a gif to show it :

https://user-images.githubusercontent.com/36560490/142870429-ae9b4399-5b27-4b09-a635-a19c010dfc88.mp4

 
and when i try to control using the keyboard this assert fails : 
```
triangle: /home/thegeeko/projects/geg/geg/vendor/imgui/imgui.cpp:10328: void ImGui::NavMoveRequestApplyResult(): Assertion `g.NavTabbingResultFirst.ID != 0' failed. 
```

**Comment by ocornut** [comment]
> and when i try to control using the keyboard this assert fails :

I think this is the recent bug we fixed on Nov 10: a9ea1ae85 (#4449)

**Comment by thegeeko** [comment]
updated to the last commit and the assert doesn't fail anymore still can't control anything tho ..

**Comment by thegeeko** [comment]
solved a bug .. i was calling ImGui::newFrame before rendering, thanks for the help

**Comment by grazianobolla** [comment]
In the examples it is called before rendering...
