### ISSUE TITLE
Vulkan function loader feature might conflict with app's similar functionality

### ISSUE THREAD

**Issue by kennyalive** [ocornut/imgui#4854]
**Version/Branch of Dear ImGui:**
Version: 1.87 WIP
Branch: master

**Renderer:**
imgui_impl_vulkan.cpp

**Compiler:**
VS 2022

**My concern:**
Crash when ImGui calls vulkan function when volk library is used to load function pointers.

~~ImGui defines vulkan function pointers using official names if ```VK_NO_PROTOTYPES``` is defined as part of custom function loader feature. For example, ```vkAllocateCommandBuffers``` name will be defined if ```VK_NO_PROTOTYPES```  is defined.~~

~~This might create a conflict with application's own vulkan function loader functionality. For example, [volk](https://github.com/zeux/volk) library defines ```VK_NO_PROTOTYPES``` and it also defines function pointers using official names. ```vkAllocateCommandBuffers``` function will be defined both by the application and by the _ImGui_. This leads to violation of single definition rule and in my use case it leads to runtime crash.~~

~~For my use case I fixed the issue by disabling the part of _ImGui_ code that defines/initialize function pointers. I'm not sure what's the best way to ensure that _ImGui_ vulkan function loader coexist with app's similar functionality and if it's in the scope of _ImGui_ library at all, so I'm writing this mostly with informative purpose. One possible solution is not to declare function pointers globally with official names or to put those pointers into a structure.~~

**Comment by ocornut** [comment]
The function pointers are defined static so they shouldn’t interfer with equivalent ones used by other compilation unit. Are you trying to include both this .cpp file and eg: volk headers in a same compilation unit ?

**Comment by kennyalive** [comment]
No I don't try to do that. I probably provided wrong reason what's going on, sorry, as you said imgui_impl_vulkan.cpp uses static to define function pointers, so it's not a single definition rule problem. I think the following happens: I use volk library and it defines VK_NO_PROTOTYPES. Then imgui_impl_vulkan.cpp defines static function pointers due VK_NO_PROTOTYPES codepaths.
So the problem as I see it now that it's possible to activate ImGui function loader feature even if you don't want it to be active. 
Now it crashes because ImGui vulkan function pointers are not initialized and I probably need to use ```ImGui_ImplVulkan_LoadFunctions```.

I think the thing that is not obvious in this design (and the reason why I was confused) is that by using dynamic function loading for your app you probably will also need to setup function loader for ImGui. But it was not obvious from documentation, it looked like it's an orthogonal feature. Initially I was quite surprised that I had crash - vkCreateSampler worked in my app's function but crashed in ImGui (and in ImGui version it was not-null function address, probably the address of static function from loader - calling it led to crash, not sure why - could be because at that point I already initialized all stuff with volk and after that point it's not clear if statically linked part will work). Only when I looked at assembly it was clear what's going on.

**Comment by kennyalive** [comment]
Here what I see in the debugger.

At first function from my app is called
![image](https://user-images.githubusercontent.com/4964024/147890418-4f8d1fba-f3d0-401d-8c7b-95d8a069ed16.png)


And later we get to ImGui initialization. The compiler does not try to dereference vkCreateSampler pointer but calls it directly. 
![image](https://user-images.githubusercontent.com/4964024/147890449-e75ab28f-9cdd-4177-87b6-102c782f278e.png)

**Comment by yelibumeng** [comment]
@kennyalive  hi i get the same error，how to fix this question(also use volk), help ！！

**Comment by kennyalive** [comment]
https://github.com/kennyalive/vulkan-base/commit/65113bfffffb317b8c355b7abd13bf3ad361e03b

**Comment by yelibumeng** [comment]
> 

thanks i will try it

**Comment by yelibumeng** [comment]
@kennyalive  thanks!!!!!, it run now

**Comment by artyomd** [comment]
I just stumbled into this problem and I think I found a very simple solution. `IMGUI_IMPL_VULKAN_NO_PROTOTYPES` this definition enables `VK_NO_PROTOTYPES` for the vulkan.h include of imgui. (Obviously, you can add the  `VK_NO_PROTOTYPES` define for the entire project, but it is a nice touch if you want something specific for imgui). After that, if you try to compile you will get a message like this
```
imgui-src/backends/imgui_impl_vulkan.cpp:1033: bool ImGui_ImplVulkan_Init(ImGui_ImplVulkan_InitInfo*, VkRenderPass): Assertion `g_FunctionsLoaded && "Need to call ImGui_ImplVulkan_LoadFunctions() if IMGUI_IMPL_VULKAN_NO_PROTOTYPES or VK_NO_PROTOTYPES are set!"' failed.
```
So I added a call to `ImGui_ImplVulkan_LoadFunctions`
```cpp
  ImGui_ImplVulkan_LoadFunctions([](const char *function_name, void *vulkan_instance) {
    return vkGetInstanceProcAddr(*(reinterpret_cast<VkInstance *>(vulkan_instance)), function_name);
  }, &vulkan_instance_);
```
In this compilation unit, all the vulkan functionality is provided by volk (yes, I am using volk, too :) but this approach is applicable for all the loaders), so we can easily delegate all the loaded function to imgui, without changing anything in imgui sources.
Hope this helps somebody, and pls let me know if I missed anything :raised_hands:

**Comment by zhivkob** [comment]
@artyomd Much more elegant than what I initially did, which was fiddle with the original implementation. Thanks for pointing me in the right direction!

**Comment by Markyparky56** [comment]
To expand on @artyomd's solution, if you are using volk with "optimised device calls" (`volkLoadInstanceOnly` + `volkLoadDevice`) you might want to use `vkGetDeviceProcAddr` rather than `vkGetInstanceProcAddr` for all requested functions. Except `vkGetDeviceProcAddr` can't fetch certain functions that are instance-specific!

I found passing in a method to fetch both Instance and Device handles and fetching for both, then selecting the device proc address if available works well enough.

ex:
```
auto funcLoader = [](const char* funcName, void* engine) 
  {
    FCEngine* fcEngine = reinterpret_cast<FCEngine*>(engine);
    PFN_vkVoidFunction instanceAddr = vkGetInstanceProcAddr(fcEngine->GetVulkanInstance(), funcName);
    PFN_vkVoidFunction deviceAddr = vkGetDeviceProcAddr(fcEngine->GetVulkanDevice(), funcName);
    return deviceAddr ? deviceAddr : instanceAddr;
  };
const bool funcsLoaded = ImGui_ImplVulkan_LoadFunctions(funcLoader, this);
```

Perhaps there is a more elegant way, but since this is a one-and-done function with a very limited number of functions being requested, I'm happy.

**Comment by azer89** [comment]
I also got the same error because I am using volk.

`access violation executing location` when executing `VkCreateSampler()`

Fixed using the solution described by @artyomd 

Thanks!

**Comment by ocornut** [comment]
@kennyalive, @adalsteinnh can you clarify why you cannot use the solutions highlighted above, aka using `IMGUI_IMPL_VULKAN_NO_PROTOTYPE` + calling `ImGui_ImplVulkan_LoadFunctions()` to make it use Volk?

It seems that this would work out of the box.

**Comment by ocornut** [comment]
I have pushed b720c0f which adds support for `#define IMGUI_IMPL_VULKAN_USE_VOLK`
Both GLFW+Vulkan and SDL+Vulkan also now supports Volk optionally, which will make it easier to test forward.

See my reasoning in https://github.com/ocornut/imgui/pull/6582#issuecomment-2066582450 after why I didn't merge the `IMGUI_IMPL_VULKAN_CUSTOM_HEADER` version.

Thanks for your help!

**Comment by kennyalive** [comment]
> can you clarify why you cannot use the solutions highlighted above, aka using IMGUI_IMPL_VULKAN_NO_PROTOTYPE + calling ImGui_ImplVulkan_LoadFunctions() to make it use Volk?

@ocornut I probably never tried it, since my ad-hoc solution worked for me. I updated ImGui with the latest code and `IMGUI_IMPL_VULKAN_USE_VOLK` option works great for me. Thank you for implementing it.

**Comment by shabaazxh** [comment]
> > can you clarify why you cannot use the solutions highlighted above, aka using IMGUI_IMPL_VULKAN_NO_PROTOTYPE + calling ImGui_ImplVulkan_LoadFunctions() to make it use Volk?
> 
> @ocornut I probably never tried it, since my ad-hoc solution worked for me. I updated ImGui with the latest code and `IMGUI_IMPL_VULKAN_USE_VOLK` option works great for me. Thank you for implementing it.

do we just `#define IMGUI_IMPL_VULKAN_USE_VOLK ` before including imgui? this is what im currently doing but still facing the same issues from [https://github.com/ocornut/imgui/issues/4854#issue-1092081780](url)

**Comment by renelindsay** [comment]
I'm using a custom loader called vulkan_wrapper.h/cpp, instead of volk, but they are very similar, so I'm suffering from the same issue.  The problem is, custom loaders come with their own prototypes, which conflicts with the ones in vulkan.h.  Luckily, the Vulkan team thought of this, and provided the VK_NO_PROTOTYPES macro, to disable the prototypes in Vulkan.h.  Unfortunately, Dear ImGui detects VK_NO_PROTOTYPES, and proceeds to re-declare these prototypes, which then break any custom loaders!  This makes it impossible to use custom loaders with ImGui, which I think is exactly the opposite of what the new IMGUI_IMPL_VULKAN_NO_PROTOTYPES feature was actually trying to accomplish.
The easiest solution is to simply roll back to the previous version of the Vulkan backend from imgui v1.80.
Of course this is a problem if you actually need features from newer backends.
In that case, you have to manually delete or comment out the vulkan prototypes in imgui_impl_vulkan.cpp, delete the ImGui_ImplVulkan_LoadFunctions function, as well as the three IM_ASSERT functions that check if g_FunctionsLoaded == true.
What a PITA!

**Comment by ocornut** [comment]
A PR for this would be good, as well as possibly in the PR please include an extra commit (which I won't merge but will keep aside) that include code for using another loader than Volk. Thank you!

**Comment by renelindsay** [comment]
When vulkan_wrapper is used, it defines VK_NO_PROTOTYPES, to prevent conflicts with vulkan.h.
However, this triggers your loader to define prototypes as well, which reintroduces conflicts.
To prevent this, you could check for IMGUI_IMPL_VULKAN_NO_PROTOTYPES instead.
While pulling the latest imgui, I noticed you already mostly fixed this in release 1.90.6.
As far as I can tell, Just one more change is needed:

In imgui_impl_vulkan.cpp, line 112, I suggest changing
    `#if defined(VK_NO_PROTOTYPES) && !defined(VOLK_H_)`
to:
    `#if defined(IMGUI_IMPL_VULKAN_NO_PROTOTYPES) && !defined(VOLK_H_)`

I'll make a PR once I've done more thorough testing.
