### ISSUE TITLE
Tables: SizingFixedFit flag not honored correctly for synched tables (widths of one bleeds into next one)

### ISSUE THREAD

**Issue by Ifry** [ocornut/imgui#7218]
### Version/Branch of Dear ImGui:

Version 1.90.1, Branch: master

### Back-ends:

imgui_impl_dx11.cpp

### Compiler, OS:

Windows 11 + MSVC 2022

### Details:

**My Issue/Question:**

When I use ImGuiTableFlags_SizingFixedFit without ImGuiTableFlags_Resizable, table columns are not synchronized and have different widths. It appears as if the widths are swapped between the first and second table.

The expected behavior is to have both tables with the same width of first column adjusted to fit the text "Very very long text 1"

### Screenshots/Video:

![изображение](https://github.com/ocornut/imgui/assets/3999844/c3ba7fa0-50c9-4d26-b768-f8c691dd43f6)

### Minimal, Complete and Verifiable Example code:

```cpp
            ImGui::Begin("Synced tables test");

            if (ImGui::BeginTable("test_table", 2, ImGuiTableFlags_Borders | ImGuiTableFlags_SizingFixedFit))
            {
                ImGui::TableNextColumn();
                ImGui::Text("Very very long text 1");

                ImGui::TableNextColumn();
                ImGui::Text("Text 1");

                ImGui::TableNextColumn();
                ImGui::Text("Very very long text 2");

                ImGui::TableNextColumn();
                ImGui::Text("Text 2");

                ImGui::EndTable();
            }

            if (ImGui::BeginTable("test_table", 2, ImGuiTableFlags_Borders | ImGuiTableFlags_SizingFixedFit))
            {
                ImGui::TableNextColumn();
                ImGui::Text("Text 1");

                ImGui::TableNextColumn();
                ImGui::Text("Text 2");

                ImGui::TableNextColumn();
                ImGui::Text("Text 1");

                ImGui::TableNextColumn();
                ImGui::Text("Text 2");

                ImGui::EndTable();
            }

            ImGui::End();
```

**Comment by ScottDennison** [comment]
As a new user of ImGui, I thought I was going insane
But this exactly matches what I am seeing

**Comment by Ifry** [comment]
> the correct result after a fix is that the first column of both tables will always be wide enough to hold the "Very very long text 1" bit

This is exactly what i wanted

**Comment by ScottDennison** [comment]
I can't answer for OP, but at least in my case
> the correct result after a fix is that the first column of both tables will always be wide enough to hold the "Very very long text 1" bit, and I presume this isn't what you want
This is **exactly** what I wanted.

I am having the tables be children of treenodes (via TreeNodeEx with NoPush), with all tables being the same tree depth. The tables do not have borders (it just looks like columns of text), and I was aiming for the columns to have the same positioning.

**Comment by ocornut** [comment]
I have pushed a fix for this d3c3514
Will try to write a proper automated test for it later so I am keeping this open for now.

**Comment by ocornut** [comment]
Pushed test for this too:
https://github.com/ocornut/imgui_test_engine/commit/e7cf4913cfbca3ec26727499c62d04e5db718e15

**Comment by ScottDennison** [comment]
Unfortunately, having updated the codebase that I was experiencing this issue in to v1.90.5, the issue remains.

The only notable difference from OP's original issue, is for me, the short text is on the first row and the long text is on the second row. I'll see if simply reordering the rows from OP's MCVE is enough to reproduce it, and if so, report back here.

**Comment by ScottDennison** [comment]
In fact, I am seeing this in the imgui demo (which shows v1.90.5 at the top)
![demo](https://github.com/ocornut/imgui/assets/885057/dcada35b-ff72-4078-9197-e8c60c298980)
Note that when expanding synced instance 1, synced instance 0 gains the extra blank space (good), but instance 1 does not and has any 2 digit cells truncated.

**Comment by ScottDennison** [comment]
![image](https://github.com/ocornut/imgui/assets/885057/34702af0-8b27-416b-be75-41e9f5e7b39c)
Confirming just swapping the table order in the original MCVE is enough to re-trigger the issue in v1.90.5

New MCVE:
```cpp
            ImGui::Begin("Synced tables test");

            if (ImGui::BeginTable("test_table", 2, ImGuiTableFlags_Borders | ImGuiTableFlags_SizingFixedFit))
            {
                ImGui::TableNextColumn();
                ImGui::Text("Text 1");

                ImGui::TableNextColumn();
                ImGui::Text("Text 2");

                ImGui::TableNextColumn();
                ImGui::Text("Text 1");

                ImGui::TableNextColumn();
                ImGui::Text("Text 2");

                ImGui::EndTable();
            }

            if (ImGui::BeginTable("test_table", 2, ImGuiTableFlags_Borders | ImGuiTableFlags_SizingFixedFit))
            {
                ImGui::TableNextColumn();
                ImGui::Text("Very very long text 1");

                ImGui::TableNextColumn();
                ImGui::Text("Text 1");

                ImGui::TableNextColumn();
                ImGui::Text("Very very long text 2");

                ImGui::TableNextColumn();
                ImGui::Text("Text 2");

                ImGui::EndTable();
            }

            ImGui::End();
```

**Comment by ocornut** [comment]
Sorry for my late reaction!
Pushed another fix e648dbb59d24c29a2e2ac964777822e96befd808
And amended regression test https://github.com/ocornut/imgui_test_engine/commit/3a02551c2d413b78ca73d5b1561123829531259d

Hopefully this is right this time!

**Comment by ocornut** [comment]
Pushed a fix for a regression introduced by this #8045, fix f3d242a
