### ISSUE TITLE
GLFW: platform window depth change without focus change leads to incorrect hovering heuristic (GLFW <3.3) (was: The mouse will penetrate front-most window and interact one behind it)

### ISSUE THREAD

**Issue by LOWRUI** [ocornut/imgui#9038]
### Version/Branch of Dear ImGui:

v1.92.3-docking

### Back-ends:

imgui_impl_glfw.cpp + imgui_impl_opengl3.cpp

### Compiler, OS:

Windows11 + MSVC 2022

### Full config/build information:

```cpp
Dear ImGui 1.92.3 (19230)
--------------------------------
sizeof(size_t): 8, sizeof(ImDrawIdx): 2, sizeof(ImDrawVert): 20
define: __cplusplus=199711
define: _WIN32
define: _WIN64
define: _MSC_VER=1944
define: _MSVC_LANG=201402
define: IMGUI_HAS_VIEWPORT
define: IMGUI_HAS_DOCK
--------------------------------
io.BackendPlatformName: imgui_impl_glfw (3200)
io.BackendRendererName: imgui_impl_opengl3
io.ConfigFlags: 0x00000483
 NavEnableKeyboard
 NavEnableGamepad
 DockingEnable
 ViewportsEnable
io.ConfigViewportsNoDecoration
io.ConfigNavCaptureKeyboard
io.ConfigInputTextCursorBlink
io.ConfigWindowsResizeFromEdges
io.ConfigMemoryCompactTimer = 60.0
io.BackendFlags: 0x0000141E
 HasMouseCursors
 HasSetMousePos
 PlatformHasViewports
 RendererHasVtxOffset
 RendererHasTextures
 RendererHasViewports
--------------------------------
io.Fonts: 1 fonts, Flags: 0x00000000, TexSize: 512,128
io.Fonts->FontLoaderName: stb_truetype
io.DisplaySize: 1280.00,800.00
io.DisplayFramebufferScale: 1.00,1.00
--------------------------------
style.WindowPadding: 8.00,8.00
style.WindowBorderSize: 1.00
style.FramePadding: 4.00,3.00
style.FrameRounding: 0.00
style.FrameBorderSize: 0.00
style.ItemSpacing: 8.00,4.00
style.ItemInnerSpacing: 4.00,4.00
```

### Details:

**The operation logic between the sub-window and the main window is abnormal**
Open the sub-window, move it to the edge, and then perform a "CTRL+left mouse button" click operation on the window bar. At this point, the sub-window appears behind the main window. Now, there will be a situation where the mouse interaction is triggered on the main window but is displayed on the sub-window

The video is in the zip file. I'm not sure why uploading the video directly to github.com shows a failure

### Screenshots/Video:

[20251029.zip](https://github.com/user-attachments/files/23205489/20251029.zip)

**Comment by ocornut** [comment]
This was fixed in dear imgui 1.92.4 (see #8948) or if you update to GLFW 3.4.

**Comment by LOWRUI** [comment]
> This was fixed in dear imgui 1.92.4 (see [#8948](https://github.com/ocornut/imgui/issues/8948)) or if you update to GLFW 3.4.

This issue still exists in version 1.92.4, where the mouse can control the lower-level child windows. However, updating to GLFW 3.4 resolves the problem

**Comment by ocornut** [comment]
I can confirm it stills happens on backends not supporting `ImGuiBackendFlags_HasMouseHoveredViewport`.

- GLFW 3.2: happens.
- GLFW 3.3+: does not happen.

Because set `ImGuiViewportFlags_NoFocusOnAppearing` on newly dragged viewport it doesn't take focus, and a result the Ctrl+click on main viewport results in no specific input from the point of view of our backend, so our heuristic still think the independent viewport is top-most.

It's a complex problem to solve in our current architecture as we conflate focused and z-order, and I'm not sure we can work on a better fix for GLFW 3.2, but I'll keep this open for now.

The natural fix would be that we stop relying on `ImGuiViewportFlags_NoFocusOnAppearing` as much:
- For GLFW it would mean a workaround to ignore keyboard release events sent on focus loss (may be platform dependant).
- And naturally it would have other side-effects that needs investigation as this was added for multiple reasons.
